name: Burger-War Image Build & Test

# トリガーイベントの指定
on:
  # 指定ブランチで指定ファイルがPUSHされたときに実行する
  push:
    paths:
      - 'docker/core/**'
      - 'docker/sim/**'
      - 'docker/robo/**'
      - 'burger_navigation/**'
      - 'burger_war_dev/**'
      - '.github/workflows/image-test.yml'

  # ブラウザ上からの手動実行設定
  workflow_dispatch:

# テスト実行用コメント修正

# 環境変数の設定
env:
  DOCKER_BUILDKIT: 1
  RESISTRY_URL: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME_CORE: burger-war-core
  IMAGE_NAME_SIM: burger-war-sim
  IMAGE_NAME_ROBO: burger-war-robo
  DOCKER_ROOT_DIR: ./docker
  DOCKER_FILE_CORE: ./docker/core/Dockerfile
  DOCKER_FILE_SIM: ./docker/sim/Dockerfile
  DOCKER_FILE_ROBO: ./docker/robo/Dockerfile
  # TEST_VERSION: test.${{ github.run_number }}
  TEST_LOG_ARCHIVE: test_logs-${{ github.run_number }}
  DISPLAY: ':99'
  KIT_VERSION: test.16

# 実行する処理
jobs:
  # ビルドとテストを実施し、テストにPASSすれば、仮バージョンでプッシュ
  build-test:

    runs-on: ubuntu-20.04

    steps:
      # 環境準備
      - name: Checkout repository
        uses: actions/checkout@v2

      # Dockerのversion確認
      - name: Print Docker Version
        run: |
          docker version

      # burger-warイメージのビルド
      - name: Build Core Image
        run: |
          docker build --file ${{ env.DOCKER_FILE_CORE }} --tag ${{ env.IMAGE_NAME_CORE }} --build-arg KIT_VERSION=${{ env.KIT_VERSION }} ${{ env.DOCKER_ROOT_DIR }}

      - name: Build Sim Image
        run: |
          docker build --file ${{ env.DOCKER_FILE_SIM }} --tag ${{ env.IMAGE_NAME_SIM }} ${{ env.DOCKER_ROOT_DIR }}

      - name: Build Robo Image
        run: |
          docker build --file ${{ env.DOCKER_FILE_ROBO }} --tag ${{ env.IMAGE_NAME_ROBO }} ${{ env.DOCKER_ROOT_DIR }}

      # xvfbのインストールと起動
      - name: Xvfb install and run
        run: |
          sudo apt-get install -y xvfb
          Xvfb -ac ${{ env.DISPLAY }} -screen 0 1280x780x24 &

      # burger-warのファイル準備
      - name: Create Workspace
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/catkin_ws/logs
          mkdir -p ${GITHUB_WORKSPACE}/catkin_ws/src/burger_war_dev/
          cp -r ./burger_navigation ${GITHUB_WORKSPACE}/catkin_ws/src/burger_war_dev/
          cp -r ./burger_war_dev ${GITHUB_WORKSPACE}/catkin_ws/src/burger_war_dev/
          echo "catkin_ws/ ======================================================"
          ls -la ${GITHUB_WORKSPACE}/catkin_ws
          echo "catkin_ws/src/burger_war_dev/ ==================================="
          ls -la ${GITHUB_WORKSPACE}/catkin_ws/src/burger_war_dev/

      # burger-warコンテナ起動
      - name: Launch Docker Container
        run: |
          docker run \
            --name ${{ env.IMAGE_NAME_CORE }} \
            -d \
            --privileged \
            --net host \
            --mount type=bind,src=${GITHUB_WORKSPACE}/catkin_ws/src/burger_war_dev,dst=/home/developer/catkin_ws/src/burger_war_dev \
            --mount type=bind,src=${GITHUB_WORKSPACE}/catkin_ws/logs,dst=/home/developer/catkin_ws/logs \
            --device /dev/snd \
            -v /dev/shm \
            -e DISPLAY=${{ env.DISPLAY }} \
            -e HOST_USER_ID=$(id -u) \
            -e HOST_GROUP_ID=$(id -g) \
            ${{ env.IMAGE_NAME_CORE }} \
            tail -f /dev/null
          docker ps -a
          docker logs ${{ env.IMAGE_NAME_CORE }}

      # ロボコンプロジェクトのパッケージリスト
      - name: Source Package List
        run: |
          docker exec -u developer -t ${{ env.IMAGE_NAME_CORE }} bash -l -c "ls -la /home/developer/catkin_ws/src/*"

      # ロボコンプロジェクトのビルド
      - name: Build Robot Programs
        run: |
          docker exec -u developer -t ${{ env.IMAGE_NAME_CORE }} bash -l -c "catkin build"

      # burger-warのテスト
      - name: Test Docker Image
        id: image-test
        run: |
          docker exec -u developer -t ${{ env.IMAGE_NAME_CORE }} bash -l -c "cd src/burger_war_kit && bash scripts/sim_run_test.sh" \
            && echo "::set-output name=test_result::0" \
            || echo "::set-output name=test_result::1"

      # テスト結果をArtifactにアップロードする
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TEST_LOG_ARCHIVE }}
          path: ${{ github.WORKSPACE }}/catkin_ws/logs/test_logs.tgz
          retention-days: 90

      # # ghcr.ioにログイン
      # - name: Login to ghrc.io
      #   if: steps.image-test.outputs.test_result == 0
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ secrets.GHCR_USERNAME }}
      #     password: ${{ secrets.GHCR_PASSWORD }}

      # # burger-warイメージをテストバージョンとしてプッシュ
      # - name: Push Docker Image
      #   if: steps.image-test.outputs.test_result == 0
      #   run: |
      #     # burger-war-simのプッシュ
      #     docker tag ${{ env.IMAGE_NAME_SIM }} ${{ env.RESISTRY_URL }}/${{ env.IMAGE_NAME_SIM }}:${{ env.TEST_VERSION }}
      #     docker push ${{ env.RESISTRY_URL }}/${{ env.IMAGE_NAME_SIM }}:${{ env.TEST_VERSION }}
      #     # burger-war-roboのプッシュ
      #     docker tag ${{ env.IMAGE_NAME_ROBO }} ${{ env.RESISTRY_URL }}/${{ env.IMAGE_NAME_ROBO }}:${{ env.TEST_VERSION }}
      #     docker push ${{ env.RESISTRY_URL }}/${{ env.IMAGE_NAME_ROBO }}:${{ env.TEST_VERSION }}

      # テストがNGだった場合
      - name: If Test Failed
        if: steps.image-test.outputs.test_result != 0
        run: |
          echo "::error::Test is failed!!"
          echo "::error::See step 'Test Docker Image'"
          exit 1
